### ISSUE TITLE
ValueError: Cannot find input file name

### ISSUE THREAD

**Issue by CPFelix** [NVIDIA-AI-IOT/TAO-Toolkit-Whitepaper-use-cases#3]
When I used "tao yolo_v4 export" model,Iget the follow error:
"
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/ed34e6d125608f91724fda23656f1726/execroot/ai_infra/bazel-out/k8-fastbuild/bin/magnet/packages/iva/build_wheel.runfiles/ai_infra/iva/yolo_v4/scripts/export.py", line 12, in <module>
  File "/root/.cache/bazel/_bazel_root/ed34e6d125608f91724fda23656f1726/execroot/ai_infra/bazel-out/k8-fastbuild/bin/magnet/packages/iva/build_wheel.runfiles/ai_infra/iva/common/export/app.py", line 233, in launch_export
  File "/root/.cache/bazel/_bazel_root/ed34e6d125608f91724fda23656f1726/execroot/ai_infra/bazel-out/k8-fastbuild/bin/magnet/packages/iva/build_wheel.runfiles/ai_infra/iva/common/export/app.py", line 198, in run_export
  File "/root/.cache/bazel/_bazel_root/ed34e6d125608f91724fda23656f1726/execroot/ai_infra/bazel-out/k8-fastbuild/bin/magnet/packages/iva/build_wheel.runfiles/ai_infra/iva/common/export/keras_exporter.py", line 91, in set_keras_backend_dtype
  File "/root/.cache/bazel/_bazel_root/ed34e6d125608f91724fda23656f1726/execroot/ai_infra/bazel-out/k8-fastbuild/bin/magnet/packages/iva/build_wheel.runfiles/ai_infra/iva/common/utils.py", line 227, in get_decoded_filename
ValueError: Cannot find input file name.
2021-09-06 20:12:19,781 [INFO] tlt.components.docker_handler.docker_handler: Stopping container.
"
I'm new to use the new TAO,is it stable for project in the industry?

**Comment by CPFelix** [comment]
It seems caused by didn't set env variables.
